### ISSUE TITLE
Fallback for useTitleTemplate

### ISSUE THREAD

**Issue by urrri** [JoviDeCroock/hoofd#32]
Helmet allows using defaultTitle if there is title template and no title specified.
With the hooks, if I define template, but not define title I doesnt have any title. If I define title near the template, it works, but in this case I need behavior like in  Helmet.
e.g.
template: "AppName - %s"
default title: "AppName"

if any title defined - resut is "AppName - the title"
otherwise result is "AppName" without any junk around

**Comment by cyyynthia** [comment]
I'm bringing this issue up again as #33 covers very few cases and mostly acts as a hacky way to get it to work.

Just ignoring '%s' does not solve the original issue because the template may include a separator between the title and whatever the templates wishes to put (e.g.: `%s - Website`). Here, the empty title would look like ` - Website` which is not really a good title for a webpage.

I use as a workaround the fact `useTitle` can be conditionally used as `useTitleTemplate` with a boolean, but it requires keeping track of the url and knowing in advance which pages won't have a title which is far from ideal.
```js
useTitle(url === '/' ? 'Website' : '%s - Website', url !== '/')
```

The way Helmet handles it with a separate string used as a fallback when there's no title allows way easier control of what gets in the title, and avoid having to use workarounds.
